### PR TITLE
Only publish the most recent certificates

### PR DESCRIPTION
**Pull request by jedisct1**
This only publishes the most recent, and still valid certificates for each version, in case the server was started with multiple certificates.

### CODE REVIEW

**Comment by jedisct1** [comment]
Hey Chantra, is that consistent with what you are doing in Unbound?

**Comment by chantra** [comment]
@jedisct1 I think this is a much simpler approach than I took for unbound.

In unbound there is the notion of [dnscrypt-provider-cert-rotated](https://github.com/NLnetLabs/unbound/blob/ec179380f48e901763167ce48324dbf84718d2ed/doc/Changelog#L127) which instruct unbound to handle the cert, but not to advertise it. In a distributed environment, you can leverage that to prime the new cert first, and then rotate it by moving the old cert to _rotated and moving the new cert out of _rotated. This ensure that if a client moves from one server that publishes the new cert to a server that is not yet reloaded to publish the new cert, the client will be handled even though the server is not yet advertising the new cert.

**Comment by chantra** [comment]
@jedisct1 you will need to change the unittests to handle the fact that only the most recent of each {major, minor} is being advertised.

**Comment by jedisct1** [comment]
Just discovered that there were unit tests :oops

**Comment by chantra** [comment]
:) I added them when I was messing around :p

**Comment by cofyc** [comment]
I created a fix PR to udpate test cases: https://github.com/cofyc/dnscrypt-wrapper/pull/126. @chantra PTAL, thanks!

**Comment by chantra** [comment]
@cofyc I completely forgot to check #126 . Did just now and it looks good. Thanks

**Comment by cofyc** [comment]
@chantra Good!

**Pull request merged**
